#!/usr/bin/env bash

cd `dirname $0`
source .env

echo デプロイ開始

echo
echo [1] Program Store...
rsync -av --delete ./ ${DEPLOY_APP_PATH} --rsync-path="${DEPLOY_RSYNC_PATH:-rsync}" --exclude=.env* --exclude=deploy --exclude=/storage --exclude=/vendor --exclude=.git* --exclude=.DS_Store

echo
echo [2] Storage Store...
rsync -av ./storage/ ${DEPLOY_APP_PATH}/storage --rsync-path="${DEPLOY_RSYNC_PATH:-rsync}" --exclude=.DS_Store

echo
echo デプロイ完了
