#!/usr/bin/env bash

cd `dirname $0`

DEPLOY_HOST=s2app@orion03-deploy
DEPLOY_APP_PATH=/var/host/apps/5374



usage() {
	echo Usage: $0
	exit 0
}



deploy() {
	echo デプロイ開始

	echo
	echo [1] Program Store...
	rsync -av --delete ./ ${DEPLOY_HOST}:${DEPLOY_APP_PATH} --exclude=.env* --exclude=deploy --exclude=/storage --exclude=/vendor --exclude=.git* --exclude=.DS_Store

	echo
	echo [2] Storage Store...
	rsync -av ./storage/ ${DEPLOY_HOST}:${DEPLOY_APP_PATH}/storage --exclude=.DS_Store

	echo
	echo [3] Copy env.production
	rsync -av ./.env.production ${DEPLOY_HOST}:${DEPLOY_APP_PATH}/.env

	echo
	echo デプロイ完了
}



if [ "${DEPLOY_APP_PATH}" == "" ] ; then
	usage
elif [ "$1" == "-h" -o "$1" == "--help" ] ; then
	usage
else
	deploy
fi
